version: '3'

volumes:
  cache:
    driver: local

services:
  backend:
    build: .
    ports:
      - "8080:8080"

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}

    volumes:
      - cache:/data