version: '3'

volumes:
  mongo-data:
    driver: local

services:
  backend:
    build: .
    ports:
      - "8080:8080"

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db