spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      authentication-database: ${MONGO_AUTHENTICATION_DATABASE}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
springdoc:
  override-with-generic-response: false